### ISSUE TITLE
Missing dependency, lazy-cache

### ISSUE THREAD

**Issue by nicklasb** [jonschlinkert/braces#6]
Hi,

I appears that braces tries to import lazy-cache even though there is no defined dependency.

**Comment by jonschlinkert** [comment]
what version?

**Comment by nicklasb** [comment]
Oh, I am sorry.
This is not braces fault. For some reason karma includes it in its source, but not all of its dependencies. Go figure.

Thanks, I am closing this now.

**Comment by nicklasb** [comment]
Actually it suddenly appeared in the karma source tree after an `npm update`. 
Something most have gone wrong during the initial first update.
