### ISSUE TITLE
Dot character not working as it should (escape + expansion)

### ISSUE THREAD

**Issue by wc-matteo** [jonschlinkert/braces#9]
**Input**
```
{1\\.2}
```

**Output**
```
{1\\.2}
```

**Expected**
```
{1.2}
```

***

I wanted to escape the dot to get this to work:

```
{{a,b,c},foo.bar/{a,b,c}}/**/*.baz
```

**Output**

```
[ 'c', 'foo.bar/c' ]
```

**Expected**

```
[ 'a/**/*.baz',
  'foo.bar/a/**/*.baz',
  'foo.bar/b/**/*.baz',
  'foo.bar/c/**/*.baz',
  'b/**/*.baz',
  'c/**/*.baz' ]
```

But why should I escape the dot? As far as I know, it doesn't carry any particular meaning in glob patterns...

**Comment by jonschlinkert** [comment]
Ironically I just found this bug myself while refactoring the parser. It's surprising that it hasn't been noticed before now.  thanks for the issue
